service: temu-tamu

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  profile: temuTamuAdmin
  region: ap-southeast-1
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB: ${self:custom.secrets.DB}

functions:
  app:
    handler: server.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
#
package:
  exclude:
    - coverage/**
    - .circleci/**

plugins:
  - serverless-offline
